name = "Nameless"
author = "Ozoku"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d07dc418b1fbc36b4a719f4ad53aa169cafb451e8b791d4675fa5e3b08067fa"

[versions]
forge = "40.1.93"
minecraft = "1.18.2"
